/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
"use client"
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Astronaut(props) {
  const { nodes, materials } = useGLTF('models/little_mrastronaut-transformed.glb')
  
  const modelRef= useRef()
  useFrame((state, delta, xrFrame) => {
   modelRef.current.position.y=0.5+Math.sin(state.clock.elapsedTime)*0.20;
  })
  return (
    <group {...props} dispose={null}
    ref={modelRef}
    position={[0.05,-1.5,-1]}
    scale={[15.0,15.0,15.0]}
    >
      <mesh
        name="Box032_14_-_Default_0"
        castShadow
        receiveShadow
        geometry={nodes['Box032_14_-_Default_0'].geometry}
        material={materials['14_-_Default']}
        position={[0, 0.07, -0.001]}
        rotation={[-1.396, 0, 0]}
        scale={0.001}
      />
      <mesh
        name="tyFlow007Low002_04_-_Default_0"
        castShadow
        receiveShadow
        geometry={nodes['tyFlow007Low002_04_-_Default_0'].geometry}
        material={materials['04_-_Default']}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.001}
      />
      <mesh
        name="Object005_04_-_Defaulth_0"
        castShadow
        receiveShadow
        geometry={nodes['Object005_04_-_Defaulth_0'].geometry}
        material={materials['04_-_Defaulth']}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.001}
      />
      <mesh
        name="Box033_02_-_Default_0"
        castShadow
        receiveShadow
        geometry={nodes['Box033_02_-_Default_0'].geometry}
        material={materials['02_-_Default']}
        position={[0, 0.07, -0.001]}
        rotation={[-1.396, 0, 0]}
        scale={0.001}
      />
      <mesh
        name="Box034_08_-_Default_0"
        castShadow
        receiveShadow
        geometry={nodes['Box034_08_-_Default_0'].geometry}
        material={materials['08_-_Default']}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.001}
      />
    </group>
  )
}

useGLTF.preload('models/little_mrastronaut-transformed.glb')
